apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.application.environment }}-{{ .Values.application.name }}-service"
spec:
  selector:
    app: "{{ .Values.application.environment }}-{{ .Values.application.name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
